name: scanq
description: OCR app for Korean CSAT questions
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  camera: ^0.10.0+4
  google_mlkit_text_recognition: ^0.8.0
  path_provider: ^2.0.11
  permission_handler: ^10.2.0
  image: ^4.0.17


flutter:
  uses-material-design: true
